"""This program will determine the most popular ethnic food based on demographics."""

import csv
import numpy as np
import string
import matplotlib
import matplotlib.pyplot as plt
import operator
import urllib   # urlencode function
import urllib2  # urlopen function (better than urllib version)
import json
from pprint import pprint
import pylab as plt2
from pylab import *
from matplotlib.widgets import Slider, Button, RadioButtons
import matplotlib.ticker as ticker
<<<<<<< HEAD
=======
plt.close('all')
>>>>>>> annabel



class Data(object):
	def __init__(self, filename):
		self.filename = filename

<<<<<<< HEAD
	def get_age_range(self,age_range):
		self.age_range = age_range
		return age_range
=======


def get_numpy_array(csv_file):                                                                                                                                             
	"""returns a numpy array built from the csv file. To stop numpy from crapping itself, uneven rows and columns are padded with empty strings so that all rows and            columns have the same number of elements"""                                                                                                                                 
	data = []                                                                                                                                                               
	f = open(csv_file, "rU")                                                                                                                                                     
	for row in csv.reader(f):                                                                                                                                              
		data.append(row)                                                                                                                                                    
	length = len(sorted(data,key=len, reverse=True)[0])
	#print np.array([x+[]*(length-len(x)) for x in data])  
	return np.array([x+[]*(length-len(x)) for x in data])  

def fix_data(filename):
	a = get_numpy_array(filename)
	remove = ["N/A"]
	for element in a:
		for index in range(len(element)):
			if element[index] in remove:
				element[index] = 0
	return a

def sum_by_age(filename,age_range):
	data = fix_data(filename)
	final = []
	fn = []
	for n in range(3,43):
		column_country_sum = []
		column_country = data[1:,n]
		for index in range(1,len(column_country)):
			if data[index, 44] == age_range:
				try:
					column_country_sum.append(int(data[index,n]))
				except:
					pass
		final.append(sum(column_country_sum))
	return final

def sum_countries2(filename):
	data = fix_data(filename)
	final = []
	fn = []
	for n in range(3,43):
		new2 = []
		new = data[1:,n]
		for ele in new:
			try:
				new2.append(int(ele))
			except:
				pass
		final.append(sum(new2))
	return final

def country_rank_age(filename,age_range):
	countries = ['Algeria','Argentina','Australia','Belgium','Bosnia and Herzegovia','Brazil','Cameroon','Chile','Colombia','Costa Rica','Croatia','Ecuador','England','France','Germany','Ghana','Greece','Honduras','Iran','Italy','Ivory Coast','Japan','Mexico','Netherlands','Nigeria','Portugal','Russia','South Korea','Spain','Switzerland','United States','Uruguay','China','India','Thailand','Turkey','Cuba','Ethiopia','Vietnam','Ireland']
	country_sum = sum_by_age(filename, age_range)
	country_rank = dict(zip(countries,country_sum))
	return country_rank

def country_rank(filename):
	countries = ['Algeria','Argentina','Australia','Belgium','Bosnia and Herzegovia','Brazil','Cameroon','Chile','Colombia','Costa Rica','Croatia','Ecuador','England','France','Germany','Ghana','Greece','Honduras','Iran','Italy','Ivory Coast','Japan','Mexico','Netherlands','Nigeria','Portugal','Russia','South Korea','Spain','Switzerland','United States','Uruguay','China','India','Thailand','Turkey','Cuba','Ethiopia','Vietnam','Ireland']
	country_sum = sum_countries2(filename)
	country_rank = dict(zip(countries,country_sum))
	return country_rank

def make_barplot(filename):
	"""Using a dictionary, plots a book's relative happiness in reference to the year it was published.
	Input is a list of txt files generated by the get_file function.
	file_list = list of string that correspond to .txt files"""
	D = country_rank(filename)

	for country in D:
		plt.bar(range(len(D)), D.values())
	plt.xticks(range(len(D)),D.keys(),rotation = 'vertical')
	plt.xlabel('country')
	plt.ylabel('sum of survey data')
	plt.title('Popularity of Ethnic Foods', fontsize=12)
	plt.show()


def make_interactive_plot(filename):
	young = country_rank_age("food-world-cup-data.csv",'18-29')
	medium = country_rank_age("food-world-cup-data.csv",'30-44')
	old = country_rank_age("food-world-cup-data.csv",'45-60')
	older = country_rank_age("food-world-cup-data.csv",'> 60')
	fig, ax = plt.subplots()
	D = country_rank_age(filename, '18-29')
	for country in D:
		ax.bar(range(len(D)), D.values())
	plt.xticks(range(len(D)),D.keys(),rotation = 'vertical')
	plt.xlabel('country')
	plt.ylabel('sum of survey data')
	plt.title('Popularity of Ethnic Foods', fontsize=12)
	axcolor = 'lightgoldenrodyellow'
	plt.subplots_adjust(left=0.3)
	rax = plt.axes([0.05, 0.7, 0.15, 0.15], axisbg=axcolor)
	radio = RadioButtons(rax, ('18-29', '30-44', '45-60'))

	def hzfunc(label):
		fig, ax = plt.subplots()
		plt.clf()
		hzdict = {'18-29':young, '30-44':medium, '45-60':old}
   		D = hzdict[label]
		for country in D:
			ax.bar(range(len(D)), D.values())
		plt.xticks(range(len(D)),D.keys(),rotation = 'vertical')
		plt.xlabel('country')
		plt.ylabel('sum of survey data')
		plt.title('Popularity of Ethnic Foods', fontsize=12)
		axcolor = 'lightgoldenrodyellow'
		plt.subplots_adjust(left=0.3)
		rax = plt.axes([0.05, 0.7, 0.15, 0.15], axisbg=axcolor)
		plt.show()

	radio.on_clicked(hzfunc)
	plt.show()

>>>>>>> annabel
	
	def get_numpy_array(self):                                                                                                                                             
		"""returns a numpy array built from the csv file. To stop numpy from crapping itself, uneven rows and columns are padded with empty strings so that all rows and            columns have the same number of elements"""                                                                                                                                 
		data = []      
		csv_file = self.filename                                                                                                                                                         
		f = open(csv_file, "rU")                                                                                                                                                     
		for row in csv.reader(f):                                                                                                                                              
			data.append(row)                                                                                                                                                    
		length = len(sorted(data,key=len, reverse=True)[0])
		#print np.array([x+[]*(length-len(x)) for x in data])  
		return np.array([x+[]*(length-len(x)) for x in data])  

	def fix_data(self):
		a = self.get_numpy_array()
		remove = ["N/A"]
		for element in a:
			for index in range(len(element)):
				if element[index] in remove:
					element[index] = 0
		return a

	def get_sum_by_age(self):
		data = self.fix_data()
		final = []
		fn = []
		for n in range(3,43):
			column_country_sum = []
			column_country = data[1:,n]
			for index in range(1,len(column_country)):
				if data[index, 44] == self.age_range:
					try:
						column_country_sum.append(int(data[index,n]))
					except:
						pass
			final.append(sum(column_country_sum))
		return final


	def get_country_rank_age(self):
		countries = ['Algeria','Argentina','Australia','Belgium','Bosnia and Herzegovia','Brazil','Cameroon','Chile','Colombia','Costa Rica','Croatia','Ecuador','England','France','Germany','Ghana','Greece','Honduras','Iran','Italy','Ivory Coast','Japan','Mexico','Netherlands','Nigeria','Portugal','Russia','South Korea','Spain','Switzerland','United States','Uruguay','China','India','Thailand','Turkey','Cuba','Ethiopia','Vietnam','Ireland']
		country_sum = self.get_sum_by_age()
		country_rank = dict(zip(countries,country_sum))
		return country_rank

class Plot(Data):
	def __init__(self, filename):
		super(Plot, self).__init__(filename)

	def make_barplot(self):
		"""Using a dictionary, plots a book's relative happiness in reference to the year it was published.
		Input is a list of txt files generated by the get_file function.
		file_list = list of string that correspond to .txt files"""
		#filename.add_age('18-29')
		D = self.get_country_rank_age()

<<<<<<< HEAD
		for country in D:
			plt.bar(range(len(D)), D.values())
		plt.xticks(range(len(D)),D.keys(),rotation = 'vertical')
		plt.xlabel('country')
		plt.ylabel('sum of survey data')
		plt.title('Popularity of Ethnic Foods', fontsize=12)
		plt.show()

	def make_buttons(self):
		# Make Terminate button
        young_button_ax = plt.axes([0.52, 0.01, 0.2, 0.07])
        button_young = Button(young_button_ax, '18-29')
        button_young.on_clicked(self.make_barplot)
        young_button_ax._button = button_young

data = Plot("food-world-cup-data.csv")
data.get_age_range('30-44')
print data.make_barplot()
=======

make_interactive_plot("food-world-cup-data.csv")

##############################

def get_json(url):
    """
    Given a properly formatted URL for a JSON web API request, return
    a Python JSON object containing the response to that request.
    """
    f = urllib2.urlopen(url)
    response_text = f.read()
    response_data = json.loads(response_text)
    return response_data

def get_lat_long(place_name):
    """
    Given a place name or address, return a (latitude, longitude) tuple
    with the coordinates of the given place.
    See https://developers.google.com/maps/documentation/geocoding/
    for Google Maps Geocode API URL formatting requirements.
    """
    new_place = place_name.replace(' ', "+")
    url = "https://maps.googleapis.com/maps/api/geocode/json?address=" + new_place + "&key=AIzaSyAqswAJZEulRtIHPvMpyCEYMT8XpU8uCM4" 
    json = get_json(url)
    results = json["results"][0]['geometry']['bounds']['northeast']    
    lat_long = results['lat'],results['lng']
    return lat_long #tuple

def lat_long_countries(filename):
	D = country_rank(filename) 
	for country in D:
		latlong = get_lat_long(country)
		D[country] = [D[country] , latlong[0] , latlong[1]]
	return D

def plot_on_map(filename):
	D = lat_long_countries(filename)
	m = Basemap(llcrnrlon=-360,llcrnrlat=-90,urcrnrlon=360,urcrnrlat=90,
		  resolution='c')
	m.drawcoastlines()
	m.drawcountries()
	max_size=280
	for city in D.keys():
	        x, y = m(D[city][1],D[city][2]) 
	        m.scatter(x,y,max_size*D[city][0]/D["Italy"][0],marker='o',color='r')

	axcolor = 'lightgoldenrodyellow'
	rax = axes([-10.0, 10.0, 10.0, -10.0], axisbg=axcolor)
	radio = RadioButtons(rax, ('red', 'blue', 'green'), active=0)
	def colorfunc(label):
	    D.set_color(label)
	    draw()
	radio.on_clicked(colorfunc)
	plt.show()
>>>>>>> annabel
