"""This program will determine the most popular ethnic food based on demographics."""

import csv
import numpy as np
import string
import matplotlib
import matplotlib.pyplot as plt
import operator


def get_numpy_array(csv_file):                                                                                                                                             
	"""returns a numpy array built from the csv file. To stop numpy from crapping itself, uneven rows and columns are padded with empty strings so that all rows and            columns have the same number of elements"""                                                                                                                                 
	data = []                                                                                                                                                               
	f = open(csv_file, "rU")                                                                                                                                                     
	for row in csv.reader(f):                                                                                                                                              
		data.append(row)                                                                                                                                                    
	length = len(sorted(data,key=len, reverse=True)[0])
	#print np.array([x+[]*(length-len(x)) for x in data])  
	return np.array([x+[]*(length-len(x)) for x in data])  

def fix_data(filename):
	a = get_numpy_array(filename)
	remove = ["N/A"]
	for element in a:
		for index in range(len(element)):
			if element[index] in remove:
				element[index] = 0
	return a


def sum_countries2(filename):
	data = fix_data(filename)
	final = []
	fn = []

	for n in range(3,43):
		new2 = []
		new = data[1:,n]
		for ele in new:
			try:
				new2.append(int(ele))
			except:
				pass
		final.append(sum(new2))
	return final

def country_rank(filename):
	countries = ['Algeria','Argentina','Australia','Belgium','Bosnia and Herzegovia','Brazil','Cameroon','Chile','Colombia','Costa Rica','Croatia','Ecuador','England','France','Germany','Ghana','Greece','Honduras','Iran','Italy','Ivory Coast','Japan','Mexico','Netherlands','Nigeria','Portugal','Russia','South Korea','Spain','Switzerland','United States','Uruguay','China','India','Thailand','Turkey','Cuba','Ethiopia','Vietnam','Ireland']
	country_sum = sum_countries2(filename)
	country_rank = dict(zip(countries,country_sum))
	return country_rank


def make_barplot(filename):
	"""Using a dictionary, plots a book's relative happiness in reference to the year it was published.
	Input is a list of txt files generated by the get_file function.
	file_list = list of string that correspond to .txt files"""
	D = country_rank(filename)
	#this for loop plots the publishing year and first sentiment (polarity) of each book
	#in the dictionary
	for country in D:
		plt.bar(range(len(D)), D.values())
	plt.xticks(range(len(D)),D.keys(),rotation = 'vertical')
	plt.xlabel('country')
	plt.ylabel('sum of survey data')
	plt.title('Popularity of Ethnic Foods', fontsize=12)
	plt.show()

def make_heatmap(filename):
	D = country_rank(filename)
	world_topo = r'world-countries.topo.json'
	geo_data = [{'name': 'countries', 'url': world_topo, 'feature': 'world-countries'}]
	vis = vincent.Map(geo_data=geo_data, scale=200, projection='albersUsa', data_bind='Employed_2011', data_key='FIPS', map_key={'counties': 'properties.FIPS'})
	vis.marks[0].properties.enter.stroke_opacity = ValueRef(value=0.5)
	vis.to_json('vega.json')
make_heatmap("food-world-cup-data.csv")